### ISSUE TITLE
Github key is vulnerable

### ISSUE THREAD

**Issue by milrilowe** [RFCE2209-House-Martell/je-m-appelle-martell#99]
#### Issue
We can very easily look at the requests being sent out by the client, and from there, by looking at the headers, we can see the github key being used

#### Code
Every axios request made by the client

#### Tasks
Somehow, I wasn't able to see it using Google Chrome, but I opened FireFox and was able to see the API key.
- [] Open site in FireFox
- [] Inspect the page
- [] Open Networks Tab
- [] If you do not see the requests, refresh the page
- [] Click on a request made to the API
- [] Look at request headers
![Image](https://i.imgur.com/2N7lR15.png)

A fix for this is to have your client make requests to your server (with no API key).  Then have your server pass that request along to the API (with the API key in the header) and relay the response back to the client.
